#!/usr/bin/python3
"""This module contains a class named State that inherit from
    the Base class.
    """

from sqlalchemy import Column, Integer, String, ForeignKey
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship
from model_state import State

Base = declarative_base()


class City(Base):
    """A class which is assign a table in MYSQL database

    It's has two class attributes(id and name)
    """
    __tablename__ = 'cities'
    id = Column(Integer, primary_key=True, unique=True,
                nullable=False, autoincrement=True)
    name = Column(String(128), nullable=False)
    state_id = Column(Integer, ForeignKey('states.id'), nullable=False)

City.referenced_table = relationship("State")
